services:
  # --- THE DATABASE ---
  mongo_db:
    image: mongo:4.4.18
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

    container_name: store-db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  # --- MICROSERVICES ---
  
  # Node.js Service (The Backend API)
  node-api:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
     - MONGO_URI=mongodb://mongo_db:27017/shopDB
     - JWT_SECRET=${JWT_SECRET}
     - ADMIN_USERNAME=${ADMIN_USERNAME}
     - ADMIN_PASSWORD=${ADMIN_PASSWORD}
    depends_on:
     - mongo_db
      # - kafka

  # # Go Service (The Frontend API)
  go-worker:
    build: ./frontend
    ports:
      - "8080:8080"
    depends_on:
      mongo_db:
        condition: service_healthy
    environment:
    - MONGO_URI=mongodb://mongo_db:27017/shopDB


volumes:
  mongo_data:

# To use mongo like psql:
# docker exec -it store-db mongosh  
# docker logs -f store-db